
export const SET_TOKEN = 'SET_TOKEN';
export const SET_USERINFO = 'SET_USERINFO';
export const SET_PERMISSIONLIST = 'SET_PERMISSIONLIST';
export const SET_PROJECTID = 'SET_PROJECTID';
export const SET_PLATFORM = 'SET_PLATFORM';
export const SET_TESTBUILDTYPE = 'SET_TESTBUILDTYPE';
export const SET_STEP = 'SET_STEP';
export const SET_STEPS = 'SET_STEPS';
export const REMOVE_STEPS = 'REMOVE_STEPS';
export const SETLOGININFO = 'SET_LOGININFO';
